# Generated by Django 4.2.26 on 2025-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
