# Generated by Django 4.2.26 on 2025-12-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('api', 'API'), ('cli', 'CLI')], max_length=16)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('num_contexts', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Optional identifier to group events by session.', max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data for future analytics (e.g., retrieval IDs, client info).')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
